import Link from "next/link";

const sections: Array<[string, string, string, string[]]> = [
  ["getting-started", "Getting started", "MOSAIC lets sponsors fund a bounded public software outcome. Contributors submit eligible merged work, validators inspect public evidence and the terminal target state, and deterministic contract code allocates GEN. Sponsors fund objectives; they do not pick winners.", ["Sponsors define the repository, target ref, baseline, objective and acceptance criteria.", "Contributors prove merged work with a mission-scoped wallet marker and public GitHub evidence.", "The contract is authoritative for terms, evidence status, settlement and withdrawals."]],
  ["lifecycle", "Lifecycle", "FUND → BUILD → PROVE → JUDGE → SPLIT. Mission terms are immutable after launch. Contributions can be sealed while the mission is open. After close, resolution observes the first consensus-observed settlement snapshot and either settles deterministically or remains retryable.", ["Open missions accept funding and bounded contribution records.", "Closed missions await resolution; source uncertainty moves no GEN.", "Settled missions expose terminal status, claimant outcome, roles, allocations and residuals."]],
  ["sponsors", "Sponsors", "Launch requires at least 1 GEN, a public repository, a real baseline and bounded criteria. Additional sponsors can add funding before close. Unreleased funds become pro-rata sponsor residuals only after a successful economic judgment; unresolved missions can expire and refund deterministically.", ["Close time is bounded to the protocol window.", "Sponsor totals are read from contract state, not browser storage.", "Withdrawals are pull-based and zero the balance before transfer."]],
  ["contributors", "Contributors", "Eligible work must be merged into the frozen target repository and ref. The PR author and proof-comment author are bound through stable GitHub account identity, while the wallet marker binds that account to one wallet for the mission. Find My Proof Comment is a convenience; the contract independently verifies every field.", ["Multiple contribution records are supported within the bounded mission limit.", "A PR may qualify independently in another mission, but cannot be reused twice in one mission.", "Manual numeric comment-ID entry remains available when public discovery cannot find a unique marker."]],
  ["settlement", "Settlement truth", "Terminal objective status answers what the actual settlement-state product achieved. Claimant outcome answers what eligible registered MOSAIC portfolios materially caused. They are intentionally separate: outside work can complete a product without creating a claimant payout.", ["ACHIEVED claimant outcome releases 100% to eligible contributors.", "MATERIAL_PROGRESS releases 40% to contributors and 60% to sponsor residuals.", "NOT_ACHIEVED releases 0% to contributors; positive roles are impossible.", "INSUFFICIENT_EVIDENCE remains unresolved rather than moving GEN.", "CORE / MAJOR / SUPPORTING / NO_CREDIT use fixed weights 5 / 3 / 1 / 0."]],
  ["consensus", "Consensus design", "MOSAIC chooses the narrowest consensus mechanism that fits each output. strict_eq compares exact reproducible external facts such as source identity and lineage. prompt_comparative interprets genuinely semantic capsule text. The final economically binding terminal status, claimant outcome and complete wallet-to-role map use custom run_nondet_unsafe agreement. Allocation arithmetic is deterministic contract code.", ["Rationale is explanatory and non-economic.", "Malformed, omitted or extra economic fields fail closed.", "No frontend, single model response, administrator or server chooses payouts."]],
  ["evidence", "Evidence model", "The commitment chain freezes mission terms, baseline identity, immutable PR facts, stable GitHub account identity, proof authentication, the semantic evidence snapshot, capsule, contribution record, ordered contribution root, terminal source, lineage, resolution evidence root and settlement digest. Any consequential input change must change the relevant commitment.", ["The terminal snapshot is the first consensus-observed settlement snapshot after close; it is not claimed to be the exact close_at state.", "Terminal lineage distinguishes surviving ancestry from valid non-ancestral, reverted or superseded work.", "Stored evidence remains bounded to focused engineering missions."]],
  ["causality", "Terminal causality", "Historical PR existence is not enough. A contribution still in terminal ancestry can support causal credit; a valid non-ancestral relationship can describe reverted or superseded work; outside or unregistered work can explain terminal success without entering the registered claimant role map.", ["Terminal product status and claimant causation are judged together.", "Overlapping work is represented as portfolios, not a single winner selected by the UI.", "The protocol does not promise arbitrary whole-repository transformations beyond evidence bounds."]],
  ["safety", "Failure and safety", "Public GitHub availability and anonymous rate limits are accepted dependencies. Unavailable, malformed, incomplete or oversized source fails closed, moves no GEN and can be retried. If unresolved evidence remains after the grace period, expiry/refund is deterministic. Withdrawals remain pull-based and replay-safe.", ["Accepted is not finalized; finalized without verified execution is not success.", "The browser reconstructs durable state from contract reads after writes.", "There is no privileged GitHub backend, database, queue, webhook authority or server signer."]],
  ["bounds", "Protocol bounds", "MOSAIC supports focused, bounded engineering missions. The contract enforces exact limits for sponsors, contributors, contribution records, criteria, source files, changed files, patches, total changes, capsule fields and terminal evidence. Bounds protect consensus liveness and prevent hidden cherry-picking.", ["Current terminal evidence order of magnitude: 30 files, 2,500 total changes and 24,000 patch characters.", "Oversized evidence is not silently truncated.", "Validators perform bounded public reads rather than an unbounded repository crawl."]],
  ["github", "GitHub dependency", "MOSAIC reads public GitHub directly from validators. Stable account IDs are the identity anchor; login is descriptive metadata. A public outage or rate limit is a protocol dependency, not a reason to add a privileged proxy. Retry and expiry are the recovery model.", []],
  ["contract", "Contract reference", "Public writes are open_mission, add_funding, seal_contribution, resolve_mission, expire_unresolved and withdraw. Public reads include get_mission, get_contribution, get_sponsor_total, get_balance, get_author_wallet, get_wallet_author and get_next_mission_id. The contract owns escrow, evidence state, settlement and balances.", []],
  ["deployment", "Deployment", "The canonical release runs on GenLayer Studionet chain 61999 (0xF22F), RPC https://studio.genlayer.com/api, with GEN as currency. The deployed source must equal the frozen repository source and its exact SHA-256 before the deployment is considered canonical.", ["Frontend writes use an injected EIP-1193 wallet.", "Previous addresses are historical only and must not be configured as active.", "The active address is recorded in release evidence once final deployment is verified."]],
  ["faq", "FAQ", "Same PR across missions? Yes, if each mission independently defines its own objective. Duplicate PR in one mission? Rejected. Outside contributors? They may affect terminal state but never receive MOSAIC funds without an eligible sealed portfolio. Reverted PRs? Terminal lineage exposes that relationship. Do sponsors pick winners? No: consensus binds the categorical judgment and deterministic code allocates GEN. Why 40%? It rewards meaningful unfinished progress while preserving most sponsor capital when registered claimants did not complete the objective.", []],
];

export default function DocsPage() {
  return <main className="page docs-page"><section className="page-heading"><span className="eyebrow">MOSAIC protocol manual</span><h1>Fund software outcomes with evidence you can audit.</h1><p>Public documentation for sponsors, contributors and reviewers. This manual describes implemented behavior, safety boundaries and the distinction between terminal success and claimant credit.</p></section><div className="docs-layout"><aside className="docs-toc" aria-label="Documentation contents"><strong>On this page</strong>{sections.map(([id, title]) => <a key={id} href={`#${id}`}>{title}</a>)}<Link href="/launch">Launch a mission →</Link></aside><article className="docs-content">{sections.map(([id, title, text, bullets]) => <section id={id} className="docs-section" key={id}><span className="eyebrow">{title}</span><h2>{title}</h2><p>{text}</p>{(bullets as string[]).length > 0 && <ul>{(bullets as string[]).map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}</article></div></main>;
}
